window.globals=window.globals||{};window.globals.plans=[{id:1,name:"Solo",fullName:"Solo Plan ($110+/mo) | 1 Seat",price:110,includeSeats:1,perSeatPrice:110,},{id:2,name:"Professional",fullName:"Professional Plan ($180+/mo) | 3+ Seats",price:180,includeSeats:3,perSeatPrice:60,},{id:3,name:"Agency",fullName:"Agency Plan ($400+/mo) | 10+ Seats",price:400,includeSeats:10,perSeatPrice:40,},{id:4,name:"Partner",fullName:"Enterprise Plan ($2500+/mo) | 100+ Seats",price:2500,includeSeats:100,perSeatPrice:25,}];function getPlans(){const plans=[{id:1,name:"Solo",fullName:"Solo Plan ($110+/mo) | 1 Seat",price:110,includeSeats:1,perSeatPrice:110},{id:2,name:"Professional",fullName:"Professional Plan ($180+/mo) | 3+ Seats",price:180,includeSeats:3,perSeatPrice:60},{id:3,name:"Agency",fullName:"Agency Plan ($400+/mo) | 10+ Seats",price:400,includeSeats:10,perSeatPrice:40},{id:4,name:"Partner",fullName:"Enterprise Plan ($2500+/mo) | 100+ Seats",price:2500,includeSeats:100,perSeatPrice:25}];return plans}
function getPlanAndSeatCost(numberOfSeats=10){if(isNaN(numberOfSeats)||numberOfSeats===0){numberOfSeats=1}
let pricePerSeat=0;let activePlan=null;const plans=getPlans();if(1===numberOfSeats){pricePerSeat=110;activePlan=plans[0]}else if(3<=numberOfSeats&&10>numberOfSeats){pricePerSeat=60;activePlan=plans[1]}else if(10<=numberOfSeats&&100>numberOfSeats){pricePerSeat=40;activePlan=plans[2]}else if(100<=numberOfSeats&&250>numberOfSeats){pricePerSeat=25;activePlan=plans[3]}else if(250<=numberOfSeats&&500>numberOfSeats){pricePerSeat=23;activePlan=plans[3]}else if(500<=numberOfSeats&&1000>numberOfSeats){pricePerSeat=21;activePlan=plans[3]}else if(1000<=numberOfSeats){pricePerSeat=20;activePlan=plans[3]}
return{plan:activePlan,price:pricePerSeat,}}(function($){function formatCurrencyValue(numInput,stripZeros=!0){let fixedVal=Number.parseFloat(numInput).toFixed(2);if(stripZeros){fixedVal=fixedVal.replace('.00','')}
return fixedVal}
function updateRoiWidget(){let numberOfSeats=$('.number-of-seats').val()||0;let pricePerSeat=$('.price-per-seat').val()||0;const info=getPlanAndSeatCost(numberOfSeats);if(info.plan!==null){$('.plan-type').text(info.plan.fullName);$('.per-seat-cost').text(info.price);let mrr='--';let grossMargin='--';if(numberOfSeats>0&&pricePerSeat>0){mrr=(numberOfSeats*pricePerSeat)-(numberOfSeats*info.price);mrr=formatCurrencyValue(mrr);grossMargin=Math.round(100*(pricePerSeat-info.price)/pricePerSeat)}
$('.mrr-value').text(mrr);$('.gross-margin-value').text(grossMargin)}}
function updateSelectedPlans(){let numberOfSeats=$('.plans-seat-slider').val()||1;numberOfSeats=Math.round(2.3634*Math.pow(1.0646,numberOfSeats));numberOfSeats=Math.min(1000,Math.max(3,numberOfSeats));let isYearly=$('input.is-yearly').is(':checked');let multiplier=isYearly?.9:1;let info=getPlanAndSeatCost(numberOfSeats);let totalCost=numberOfSeats*info.price;let plans=getPlans();$('.slider-number-of-seats').text(numberOfSeats);$('.slider-price-per-seat').text(formatCurrencyValue(multiplier*info.price,!1));$('.slider-total').text(formatCurrencyValue(multiplier*totalCost,!1));$('.plan-seat-cost-solo').text(formatCurrencyValue(multiplier*plans[0].perSeatPrice));$('.plan-seat-cost-pro').text(formatCurrencyValue(multiplier*plans[1].perSeatPrice));$('.plan-seat-cost-agency').text(formatCurrencyValue(multiplier*plans[2].perSeatPrice));$('.plan-seat-cost-partner').text(formatCurrencyValue(multiplier*plans[3].perSeatPrice));const planTypeTotalTemplate='Total ${total}/ '+(isYearly?'year':'month');if(isYearly){multiplier*=12}
$('.plan-seat-cost-solo-total').text(planTypeTotalTemplate.replace('{total}',formatCurrencyValue(multiplier*plans[0].perSeatPrice*plans[0].includeSeats)));$('.plan-seat-cost-pro-total').text(planTypeTotalTemplate.replace('{total}',formatCurrencyValue(multiplier*plans[1].perSeatPrice*plans[1].includeSeats)));$('.plan-seat-cost-agency-total').text(planTypeTotalTemplate.replace('{total}',formatCurrencyValue(multiplier*plans[2].perSeatPrice*plans[2].includeSeats)));$('.plan-seat-cost-partner-total').text(planTypeTotalTemplate.replace('{total}',formatCurrencyValue(multiplier*plans[3].perSeatPrice*plans[3].includeSeats)));$('.plan-box').removeClass('is-selected').eq(info.plan.id-1).addClass('is-selected');$('.plan-color').removeClass('professional agency partner').addClass(info.plan.name.toLowerCase())}
$(document).ready(function(){$('.calculator-input').on({change:updateRoiWidget});$('.plans-seat-slider').on({change:updateSelectedPlans,input:updateSelectedPlans});$('input.is-yearly').on({change:updateSelectedPlans})})})(jQuery)